In [4]:
# les notebooks vivent dans notebooks/ : on se replace à la racine PythonIPM
# pour que les chemins relatifs (EHCVM/, sorties/) et les imports du pipeline marchent
import os, sys
from pathlib import Path

RACINE = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
os.chdir(RACINE)
sys.path.insert(0, str(RACINE / "pipeline"))

In [5]:
import pandas as pd 
from pathlib import Path

path = Path("EHCVM")

Base_Individus = pd.read_stata(path / 'Base_Individus.dta')
Base_Menage = pd.read_stata(path / 'Base_Menage.dta')
Base_Avoir = pd.read_stata(path / 'Base_avoirs_du_menage.dta')

In [51]:
Base_Avoir.head()

,grappe,menage,vague,s12q01,s12q00,s12q02,s12q03,s12q04,s12q05__0,s12q05__1,s12q05__2,s12q06,s12q07,s12q08,s12q09
0,104,3.0,2.0,Téléphone portable,1.0,oui,1.0,Oui,1.0,NaN,NaN,Neuf,2.0,8000.0,5000.0
1,104,3.0,2.0,Four à micro-onde ou électrique,1.0,non,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,104,3.0,2.0,"Cyclomoteur/Vélomoteur, motocyclette",1.0,oui,1.0,Oui,1.0,NaN,NaN,Neuf,6.0,600000.0,300000.0
3,104,3.0,2.0,Chaîne Hi Fi,1.0,non,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,104,3.0,2.0,Piano et autre appareil de musique,1.0,non,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Noms explicites et codebook

Dictionnaires de renommage des variables retenues dans les 3 bases
(`s11q54` → `type_sanitaire`, `s02q33` → `diplome_plus_eleve`, ...), établis à partir des
libellés Stata et du questionnaire CAPI vague 1. Les variables non listées gardent leur code
d'origine et restent repérables via le codebook produit plus bas.

In [52]:
MENAGE = {
    # identification et pondération
    "grappe": "grappe",
    "menage": "menage",
    "vague": "vague",
    "hhid": "id_menage",
    "hhweight": "ponderation_menage",
    "hhsize": "taille_menage",
    "region": "region",
    "milieu": "milieu",
    "dtot": "conso_totale_annuelle",
    "pcexp": "depense_par_tete",
    "zref": "seuil_pauvrete_national",
    # logement (section 11)
    "s11q01": "type_logement",               # 11.01
    "s11q02": "nb_pieces",                   # 11.02
    "s11q04": "statut_occupation_logement",  # 11.04
    "s11q18": "materiau_mur",                # 11.18
    "s11q19": "materiau_toit",               # 11.19
    "s11q20": "materiau_sol",                # 11.20
    # eau
    "s11q21": "connecte_reseau_eau",         # 11.21
    "s11q26a": "source_eau_boisson_seche",   # 11.26a
    "s11q26b": "source_eau_boisson_pluies",  # 11.26b
    "s11q27": "distance_source_eau_seche",   # 11.27
    # électricité et éclairage
    "s11q33": "connecte_reseau_electrique",  # 11.33
    "s11q37": "source_eclairage",            # 11.37
    # combustibles de cuisson (11.52, choix multiple ordonné : 1 = principal)
    "s11q52__1": "combustible_bois_ramasse",
    "s11q52__2": "combustible_bois_achete",
    "s11q52__3": "combustible_charbon",
    "s11q52__4": "combustible_gaz",
    "s11q52__5": "combustible_electricite",
    "s11q52__6": "combustible_petrole",
    "s11q52__7": "combustible_dechets_animaux",
    "s11q52__8": "combustible_autre",
    # assainissement
    "s11q53": "evacuation_ordures",          # 11.53
    "s11q54": "type_sanitaire",              # 11.54
    "s11q55": "sanitaire_partage",           # 11.55
    "s11q57": "evacuation_excrements",       # 11.57
    "s11q59": "evacuation_eaux_usees",       # 11.59
    # TIC
    "s11q45": "connecte_internet",           # 11.45
    "s11q49": "abonnement_tv",               # 11.49
}

INDIVIDUS = {
    # identification et démographie (section 1)
    "grappe": "grappe",
    "menage": "menage",
    "vague": "vague",
    "s01q00a": "id_membre",
    "s01q01": "sexe",                      # 1.01
    "s01q02": "lien_parente_cm",           # 1.02
    "s01q03b": "mois_naissance",           # 1.03b
    "s01q03c": "annee_naissance",          # 1.03c
    "s01q04a": "age_declare",              # 1.04a (renseigné pour 6 % des membres)
    "s01q05": "acte_naissance",            # 1.05 : 1 oui, 2 non, 3 NSP
    "s01q07": "situation_matrimoniale",    # 1.07
    "s01q11": "present_menage",            # 1.11
    "s01q12": "reside_6_mois",             # 1.12
    "s01q14": "religion",                  # 1.14
    "s01q15": "nationalite",               # 1.15
    "s01q36": "possede_telephone",         # 1.36
    # éducation (section 2)
    "s02q01__1": "lit_francais",           # 2.01
    "s02q02__1": "ecrit_francais",         # 2.02
    "s02q02a__1": "comprend_francais",     # 2.02a
    "s02q03": "a_frequente_ecole",         # 2.03
    "s02q12": "scolarise_2020_2021",       # 2.12
    "s02q08a": "scolarise_2021_2022",      # 2.08a
    "s02q13": "raison_non_scolarisation",  # 2.13
    "s02q29": "niveau_instruction",        # 2.29
    "s02q31": "derniere_classe",           # 2.31
    "s02q33": "diplome_plus_eleve",        # 2.33 : 0 aucun, 1 CEPE, 2 BEPC, ...
    # santé (section 3)
    "s03q01": "probleme_sante_30j",        # 3.01
    "s03q05": "consultation_sante_30j",    # 3.05
    "s03q06": "raison_non_consultation",   # 3.06 : 2 « Trop cher », 8 « Manque d'argent »
    "s03q32": "assurance_maladie",         # 3.32
    "s03q38": "moustiquaire",              # 3.38
    # emploi (section 4A)
    "s04q06": "travail_champ_7j",          # 4.06
    "s04q07": "travail_commerce_7j",       # 4.07
    "s04q08": "travail_salarie_7j",        # 4.08
    "s04q09": "travail_apprenti_7j",       # 4.09
    "s04q10": "a_travaille_7j",            # 4.10 : vrai si oui à 4.06-4.09
    "s04q11": "emploi_mais_absent_7j",     # 4.11
    "s04q12": "raison_non_travail_7j",     # 4.12
    "s04q15": "recherche_emploi_30j_a",    # 4.15 (branche : n'a pas travaillé)
    "s04q17": "recherche_emploi_30j_b",    # 4.17 (branche : sans emploi)
    "s04q19": "disponible_emploi",         # 4.19 (posé aux non-chercheurs)
    "s04q20": "delai_disponibilite",       # 4.20 (posé si 4.17 ou 4.19 = oui)
    "s04q21": "mois_sans_emploi",          # 4.21
    "s04q22": "mois_de_recherche",         # 4.22
}

AVOIRS = {
    "grappe": "grappe",
    "menage": "menage",
    "vague": "vague",
    "s12q01": "code_bien",       # 12.01 (28 = voiture, 35 = portable, ...)
    "s12q02": "possede_bien",    # 12.02 : 1 oui, 2 non
    "s12q03": "nombre_biens",    # 12.03
    "s12q09": "valeur_actuelle", # 12.09
}

# échelle FIES de la FAO (section 8A) : 1 Oui, 2 Non, 98 NSP, 99 Refus
SECURITE_ALIMENTAIRE = {
    "grappe": "grappe",
    "menage": "menage",
    "vague": "vague",
    "s08aq01": "fies_inquietude",           # 8A.01  sévérité légère
    "s08aq02": "fies_pas_sain",             # 8A.02  légère
    "s08aq03": "fies_peu_varie",            # 8A.03  légère
    "s08aq04": "fies_saute_repas",          # 8A.04  modérée
    "s08aq05": "fies_mange_moins",          # 8A.05  modérée
    "s08aq06": "fies_plus_de_nourriture",   # 8A.06  modérée
    "s08aq07": "fies_faim",                 # 8A.07  sévère
    "s08aq07a": "fies_faim_frequence",      # 8A.07a
    "s08aq08": "fies_journee_sans_manger",  # 8A.08  sévère
    "s08aq08a": "fies_journee_frequence",   # 8A.08a
}

BASES = {
    "Base_Menage.dta": MENAGE,
    "Base_Individus.dta": INDIVIDUS,
    "Base_avoirs_du_menage.dta": AVOIRS,
    "Base_securite_alimentaire.dta": SECURITE_ALIMENTAIRE,
}

# renommage des bases déjà chargées (les variables non documentées gardent leur code)
Base_Individus = Base_Individus.rename(columns=INDIVIDUS)
Base_Menage = Base_Menage.rename(columns=MENAGE)
Base_Avoir = Base_Avoir.rename(columns=AVOIRS)

Base_Avoir.columns

Index(['grappe', 'menage', 'vague', 'code_bien', 's12q00', 'possede_bien',
       'nombre_biens', 's12q04', 's12q05__0', 's12q05__1', 's12q05__2',
       's12q06', 's12q07', 's12q08', 'valeur_actuelle'],
      dtype='str')

In [53]:
def codebook(fichier, noms):
    """Code, nom explicite, libellé Stata et modalités — lit seulement l'en-tête du .dta."""
    r = pd.io.stata.StataReader(path / fichier)
    libelles = r.variable_labels()
    valeurs = r.value_labels()
    jeux = dict(zip(r._varlist, r._lbllist))
    return pd.DataFrame({
        "variable": r._varlist,
        "nom_explicite": [noms.get(v, "") for v in r._varlist],
        "libelle": [libelles.get(v, "") for v in r._varlist],
        "modalites": [valeurs.get(jeux.get(v)) for v in r._varlist],
    })


for fichier, noms in [("Base_Individus.dta", INDIVIDUS), ("Base_Menage.dta", MENAGE),
                      ("Base_avoirs_du_menage.dta", AVOIRS)]:
    cb = codebook(fichier, noms)
    cb.to_csv(f"codebook_{fichier.replace('.dta', '')}.csv", index=False)
    print(fichier, len(cb), "variables,", (cb.nom_explicite != "").sum(), "documentées")

cb.head(10)

Base_Individus.dta 406 variables, 44 documentées
Base_Menage.dta 309 variables, 38 documentées
Base_avoirs_du_menage.dta 15 variables, 7 documentées

,variable,nom_explicite,libelle,modalites
0,grappe,grappe,grappe,None
1,menage,menage,Identifiant du ménage,None
2,vague,vague,Vague,None
3,s12q01,code_bien,12.01.CODE D'ARTICLE,"{1: 'Salon (Fauteuils et table basse)', 2: 'Table à manger (table + chaises)', 3: 'L..."
4,s12q00,,12.00. Qui est le répondant principal de la section?,None
5,s12q02,possede_bien,12.02. Un mbre du MEN possède [EQUIPEMENT] svant en bon état de fctionement?,"{1: 'oui', 2: 'non'}"
6,s12q03,nombre_biens,12.03. Quel est le nombre de [ARTICLE]?,None
7,s12q04,,12.04. Est ce que le bien appartient à un membre du ménage en particulier?,"{1: 'Oui', 2: 'Non'}"
8,s12q05__0,,12.05. Quel est le CODE ID de la personne1 qui possède ces articles?,None
9,s12q05__1,,12.05. Quel est le CODE ID de la personne2 qui possède ces articles?,None

In [54]:
Base_Avoir.head(10)

,grappe,menage,vague,code_bien,s12q00,possede_bien,nombre_biens,s12q04,s12q05__0,s12q05__1,s12q05__2,s12q06,s12q07,s12q08,valeur_actuelle
0,104,3.0,2.0,Téléphone portable,1.0,oui,1.0,Oui,1.0,NaN,NaN,Neuf,2.0,8000.0,5000.0
1,104,3.0,2.0,Four à micro-onde ou électrique,1.0,non,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,104,3.0,2.0,"Cyclomoteur/Vélomoteur, motocyclette",1.0,oui,1.0,Oui,1.0,NaN,NaN,Neuf,6.0,600000.0,300000.0
3,104,3.0,2.0,Chaîne Hi Fi,1.0,non,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,104,3.0,2.0,Piano et autre appareil de musique,1.0,non,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,104,3.0,2.0,Radio simple/Radiocassette,1.0,oui,1.0,NaN,NaN,NaN,NaN,Neuf,4.0,15000.0,7000.0
6,104,3.0,2.0,Imprimante/Fax,1.0,non,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,104,3.0,2.0,Fer à repasser à charbon,1.0,non,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,104,3.0,2.0,Réchaud (plaque) à gaz ou électrique,1.0,non,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,104,3.0,2.0,Matelas simple,1.0,oui,2.0,NaN,NaN,NaN,NaN,Neuf,5.0,25000.0,15000.0

## Dataset de travail IPM

Sélection des seules variables utiles au calcul de l'IPM, dans les 4 bases, puis fusion.

Deux partis pris :
- **rechargement en codes bruts** (`convert_categoricals=False`) : les règles de privation se
  écrivent sur des codes (`type_sanitaire == 1`), pas sur des libellés. Les `Base_*` chargées
  plus haut restent en libellés pour l'exploration ;
- **niveau individu** (64 491 lignes) : les caractéristiques du ménage sont recopiées sur chaque
  membre. Aucune agrégation n'est faite ici, car passer au ménage suppose des conventions
  (« au moins un membre privé », qui est éligible, que faire des manquants) qui se décident
  indicateur par indicateur.

Les avoirs (format long, 45 biens × ménage) sont mis à plat sur les 8 biens du MPI.

In [55]:
CLE = ["grappe", "menage", "vague"]

# --- variables utiles à l'IPM -------------------------------------------------
IPM_INDIVIDUS = [
    "id_membre", "sexe", "lien_parente_cm", "annee_naissance", "mois_naissance",
    "age_declare", "present_menage", "reside_6_mois",
    "acte_naissance",                                            # identification
    "lit_francais", "ecrit_francais", "a_frequente_ecole",       # éducation
    "scolarise_2020_2021", "scolarise_2021_2022", "niveau_instruction",
    "diplome_plus_eleve",
    "probleme_sante_30j", "consultation_sante_30j",              # santé
    "raison_non_consultation", "assurance_maladie", "moustiquaire",
    "travail_champ_7j", "travail_commerce_7j", "travail_salarie_7j",   # emploi
    "travail_apprenti_7j", "a_travaille_7j", "emploi_mais_absent_7j",
    "raison_non_travail_7j", "recherche_emploi_30j_a", "recherche_emploi_30j_b",
    "disponible_emploi", "delai_disponibilite",
]
IPM_MENAGE = [
    "id_menage", "ponderation_menage", "taille_menage", "region", "milieu",
    "depense_par_tete", "seuil_pauvrete_national",               # contrôle monétaire
    "nb_pieces", "materiau_mur", "materiau_toit", "materiau_sol",
    "source_eau_boisson_seche", "distance_source_eau_seche",
    "source_eclairage", "combustible_gaz", "combustible_electricite",
    "type_sanitaire", "sanitaire_partage",
]
IPM_FIES = [v for v in SECURITE_ALIMENTAIRE.values() if v.startswith("fies")]
BIENS_IPM = {16: "refrigerateur", 19: "radio", 20: "television", 28: "voiture",
             29: "moto", 30: "bicyclette", 35: "telephone_portable", 37: "ordinateur"}


def charger_brut(fichier, garder):
    """Recharge le .dta en codes bruts, limité aux colonnes voulues, et renomme."""
    noms = BASES[fichier]
    codes = {v: k for k, v in noms.items()}
    d = pd.read_stata(path / fichier, columns=[codes[c] for c in garder],
                      convert_categoricals=False)
    return d.rename(columns=noms)


individus = charger_brut("Base_Individus.dta", CLE + IPM_INDIVIDUS)
menages = charger_brut("Base_Menage.dta", CLE + IPM_MENAGE)
fies = charger_brut("Base_securite_alimentaire.dta", CLE + IPM_FIES)
fies = fies.dropna(subset=CLE)          # 728 lignes entièrement vides dans cette base

# avoirs : format long (45 biens x ménage) -> une colonne par bien du MPI
avoirs = charger_brut("Base_avoirs_du_menage.dta", CLE + ["code_bien", "possede_bien"])
biens = (avoirs[avoirs.code_bien.isin(BIENS_IPM)]
         .assign(possede=lambda d: (d.possede_bien == 1).astype(int),
                 bien=lambda d: "possede_" + d.code_bien.map(BIENS_IPM))
         .pivot_table(index=CLE, columns="bien", values="possede", aggfunc="max")
         .reset_index())

ipm_data = (individus
            .merge(menages, on=CLE, how="left", validate="m:1", indicator="_menage")
            .merge(biens, on=CLE, how="left", validate="m:1")
            .merge(fies, on=CLE, how="left", validate="m:1", indicator="_fies"))

# contrôles d'appariement : tout doit être apparié
print("individus :", len(individus), "| ménages :", len(menages),
      "| ménages dans les avoirs :", len(biens), "| ménages FIES :", len(fies))
print("appariement ménage :", ipm_data._menage.value_counts().to_dict())
print("appariement FIES   :", ipm_data._fies.value_counts().to_dict())

ipm_data = ipm_data.drop(columns=["_menage", "_fies"])
print("\ndataset final :", ipm_data.shape)
ipm_data.head()

individus : 64491 | ménages : 12965 | ménages dans les avoirs : 12965 | ménages FIES : 12965
appariement ménage : {'both': 64491, 'left_only': 0, 'right_only': 0}
appariement FIES   : {'both': 64491, 'left_only': 0, 'right_only': 0}

dataset final : (64491, 71)

,grappe,menage,vague,id_membre,sexe,lien_parente_cm,annee_naissance,mois_naissance,age_declare,present_menage,...,fies_inquietude,fies_pas_sain,fies_peu_varie,fies_saute_repas,fies_mange_moins,fies_plus_de_nourriture,fies_faim,fies_faim_frequence,fies_journee_sans_manger,fies_journee_frequence
0,1,2.0,1.0,1.0,1,1,1972,1,NaN,1,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,NaN
1,1,2.0,1.0,2.0,2,2,1988,1,NaN,1,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,NaN
2,1,2.0,1.0,3.0,1,3,2006,8,NaN,1,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,NaN
3,1,2.0,1.0,4.0,2,3,1993,1,NaN,1,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,NaN
4,1,2.0,1.0,5.0,2,3,2005,1,NaN,1,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,NaN

In [56]:
ipm_data.to_stata("ipm_data_ehcvm2021.dta", write_index=False, version=118)
print("enregistré : ipm_data_ehcvm2021.dta")

# taux de non-réponse, pour repérer les variables à conventions (filtres du questionnaire)
ipm_data.isna().mean().sort_values(ascending=False).head(15).round(3)

enregistré : ipm_data_ehcvm2021.dta

raison_non_travail_7j      0.991
delai_disponibilite        0.979
age_declare                0.939
raison_non_consultation    0.904
fies_journee_frequence     0.899
recherche_emploi_30j_a     0.884
niveau_instruction         0.798
fies_faim_frequence        0.776
scolarise_2021_2022        0.772
consultation_sante_30j     0.733
disponible_emploi          0.569
recherche_emploi_30j_b     0.549
diplome_plus_eleve         0.538
scolarise_2020_2021        0.533
emploi_mais_absent_7j      0.429
dtype: float64

In [81]:
ms = pd.read_stata('matrice_situationnelle_ehcvm2021.dta')
ms.head(15)

,grappe,menage,vague,frequentation_scolaire,annee_scolarite,alphabetisation,etat_civil,assurance_maladie,chomage,electricite,...,membres_17_49,membres_17_49_alphabetises,membres_17_40,chomeurs_17_40,enfants_5_15,enfants_5_15_sans_acte,membres_assures,nb_equipements,possede_voiture,score_fies
0,1,2.0,1.0,0,0,1,0,1,0,0,...,3,2,2,0,2,0,0,3,0,0.0
1,1,3.0,1.0,0,1,1,0,1,0,0,...,1,0,1,0,0,0,0,2,0,0.0
2,1,4.0,1.0,0,1,0,0,1,0,0,...,1,1,1,0,0,0,0,3,0,0.0
3,1,5.0,1.0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,2,0,4.0
4,1,6.0,1.0,0,1,0,0,1,0,0,...,2,2,1,0,3,0,0,2,0,5.0
5,1,7.0,1.0,0,1,1,0,1,0,0,...,1,0,0,0,0,0,0,3,0,0.0
6,1,8.0,1.0,0,1,1,0,1,0,0,...,1,0,1,0,2,0,0,2,0,0.0
7,1,9.0,1.0,0,1,1,0,1,0,0,...,1,0,1,0,0,0,0,1,0,4.0
8,1,10.0,1.0,0,1,1,0,1,0,0,...,2,1,1,0,2,0,0,2,0,3.0
9,1,11.0,1.0,0,1,1,0,1,0,0,...,1,0,1,0,0,0,0,1,0,0.0
10,1,12.0,1.0,1,1,1,0,1,0,0,...,2,0,1,0,1,0,0,2,0,5.0
11,1,27.0,1.0,0,1,0,0,1,0,0,...,1,1,1,0,0,0,0,1,0,0.0
12,2,1.0,2.0,0,0,0,0,0,0,0,...,2,2,1,0,2,0,5,3,0,0.0
13,2,2.0,2.0,0,0,0,0,0,0,0,...,4,4,3,0,2,0,5,3,0,0.0
14,2,3.0,2.0,0,0,0,0,0,1,0,...,4,4,3,1,2,0,4,3,0,1.0

In [82]:
ms.columns

Index(['grappe', 'menage', 'vague', 'frequentation_scolaire',
       'annee_scolarite', 'alphabetisation', 'etat_civil', 'assurance_maladie',
       'chomage', 'electricite', 'logement', 'eau_potable', 'energie_cuisson',
       'toilette', 'biens_equipement', 'source_eclairage', 'materiau_toit',
       'materiau_mur', 'materiau_sol', 'source_eau_boisson_seche',
       'temps_aller_source_seche', 'combustible_principal', 'type_sanitaire',
       'sanitaire_partage', 'id_menage', 'ponderation_menage', 'taille_menage',
       'region', 'milieu', 'enfants_6_16', 'enfants_6_16_non_scolarises',
       'membres_17_95', 'annees_etudes_max', 'membres_17_49',
       'membres_17_49_alphabetises', 'membres_17_40', 'chomeurs_17_40',
       'enfants_5_15', 'enfants_5_15_sans_acte', 'membres_assures',
       'nb_equipements', 'possede_voiture', 'score_fies'],
      dtype='str')

In [10]:
pms = pd.read_stata("sorties/preconstruction_matrice_situationnelle.dta")
pms.head()

,grappe,menage,vague,source_eclairage,materiau_toit,materiau_mur,materiau_sol,source_eau_boisson_seche,temps_aller_source_seche,combustible_principal,...,membres_17_49,membres_17_49_alphabetises,membres_17_40,chomeurs_17_40,enfants_5_15,enfants_5_15_sans_acte,membres_assures,nb_equipements,possede_voiture,score_fies
0,1,2.0,1.0,1,3,1,1,1,NaN,gaz,...,3,2,2,0,2,0,0,3,0,0.0
1,1,3.0,1.0,1,3,1,1,1,NaN,gaz,...,1,0,1,0,0,0,0,2,0,0.0
2,1,4.0,1.0,1,3,1,1,2,NaN,bois_ramasse,...,1,1,1,0,0,0,0,3,0,0.0
3,1,5.0,1.0,1,3,1,2,2,NaN,autre,...,0,0,0,0,0,0,0,2,0,4.0
4,1,6.0,1.0,1,3,1,2,1,NaN,gaz,...,2,2,1,0,3,0,0,2,0,5.0

In [11]:
ms = pd.read_stata("sorties/matrice_situationnelle_ehcvm2021.dta")
ms.head()

,grappe,menage,vague,frequentation_scolaire,annee_scolarite,alphabetisation,etat_civil,assurance_maladie,chomage,electricite,...,eau_potable,energie_cuisson,toilette,biens_equipement,id_menage,ponderation_menage,taille_menage,region,milieu,sexe_cm
0,1,2.0,1.0,0,0,1,0,1,0,0,...,0,0,0,0,102.0,1098.117188,7,1,1,1
1,1,3.0,1.0,0,1,1,0,1,0,0,...,0,0,0,0,103.0,1098.117188,3,1,1,1
2,1,4.0,1.0,0,1,0,0,1,0,0,...,0,1,0,0,104.0,1098.117188,1,1,1,1
3,1,5.0,1.0,0,1,0,0,1,0,0,...,0,1,1,0,105.0,1098.117188,1,1,1,1
4,1,6.0,1.0,0,1,0,0,1,0,0,...,0,0,1,0,106.0,1098.117188,5,1,1,1

In [18]:
ms.info()

<class 'pandas.DataFrame'>
RangeIndex: 12965 entries, 0 to 12964
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   grappe                  12965 non-null  int32
 1   menage                  12965 non-null  float64
 2   vague                   12965 non-null  float64
 3   frequentation_scolaire  12965 non-null  int32
 4   annee_scolarite         12965 non-null  int32
 5   alphabetisation         12965 non-null  int32
 6   etat_civil              12965 non-null  int32
 7   assurance_maladie       12965 non-null  int32
 8   chomage                 12965 non-null  int32
 9   electricite             12965 non-null  int32
 10  logement                12965 non-null  int32
 11  eau_potable             12965 non-null  int32
 12  energie_cuisson         12965 non-null  int32
 13  toilette                12965 non-null  int32
 14  biens_equipement        12965 non-null  int32
 15  id_menage               12965 non-null  float32
 16  ponderation_menage      12965 non-null  float32
 17  taille_menage           12965 non-null  int8
 18  region                  12965 non-null  int8
 19  milieu                  12965 non-null  int8
 20  sexe_cm                 12965 non-null  int8
dtypes: float32(2), float64(2), int32(13), int8(4)
memory usage: 1013.0 KB